config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'browse'  => 'users#index'
  get 'mycomics' => 'static_pages#mycomics'
  get 'test'   => 'static_pages#test'
  get 'test/test1'   => 'static_pages#test1', as: :test_test1
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :comments,          only: [:create, :destroy]
  resources :comics do
    resources :pages
  end
  resources :relationships,       only: [:create, :destroy]

end

app/views/shared/_comic_form.html.erb
<%= form_for(@comic) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title, placeholder: "Create new comic..." %>
      <span class="image">
        <%= f.label :cover %>
        <%= f.file_field :image %>
        <%= f.label :summary %>
        <%= f.text_area :summary %>
      </span>
    </div>
    <%= f.submit "Create", class: "btn btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_page_form.html.erb
<%= form_for(@page) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">



        <%= f.label :summary %>
        <%= f.text_area :summary %>

    </div>
    <%= f.submit "Create", class: "btn btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.comics.count, "comic") %></span>