config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'browse'  => 'users#index'
  get 'mycomics' => 'static_pages#mycomics'
  get 'test'   => 'static_pages#test'
  get 'test/test1'   => 'static_pages#test1', as: :test_test1
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :comments,          only: [:create, :destroy]
  resources :comics do
    resources :pages
  end
  resources :relationships,       only: [:create, :destroy]

end

app/views/pages/_page.html.erb
<li id="page-<%= page.id %>">
  <span class="content"><%= page.summary %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(page.created_at) %> ago.
  </span>
</li>

app/views/pages/index.html.erb
<% @pages.each do |page| %>
      <%= link_to page.summary, [@comic, page] %>
    <% if current_user?(page.user_id) %>
        <%= link_to "delete", comic_page_path, method: :delete,
                    data: { confirm: "You sure?" } %>
    <% end %>

<% end %>

app/views/pages/new.html.erb
<% provide(:title, 'New page') %>

<div class="content_form">
  <h1>New page</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for [@comic, @page] do |f| %>
          <%= render 'shared/error_messages', object: f.object %>

          <%= f.label :summary %>
          <%= f.text_field :summary %>

          <%= f.label :page %>
          <%= f.file_field :image %>

          <%= f.submit "Upload page", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

</div>

app/views/pages/show.html.erb
<div class="section group">
  <div class="content_page">
    <div class="section group">
      <%= render 'layouts/comics_banner' %>
    </div>

    <%= render 'layouts/comic_navigation' %>


    <div class="section group">
      <div class="col span_1_of_12" push></div>
      <div class="col span_10_of_12">
        <% unless @page.image.blank? %>

            <%= image_tag @page.image, :class => "page"%>

        <% end %>
      </div>
    </div>

    <%= render 'layouts/comic_navigation' %>

    <div class="section group">
      <div class="col span_1_of_12" push></div>
      <div class="col span_10_of_12">
        <p>
          <%= yield(:author_comment) %>
        </p>
      </div>
    </div>

    <div class="section group">
      <div class="col span_1_of_12" push></div>
      <div class="col span_7_of_12">
        <%= text_area_tag(:message, "Hi, nice site", size: "10x6") %>
        <div class="col span_4_of_12" style="margin-left: 0px">
          <span class="btn btn-default btn-block btn-lg" >Send</span>
        </div>
      </div>
      <div class="col span_3_of_12">
        <span class="btn btn-primary btn-block btn-lg" >FOLLOW</span>
        <span class="btn btn-primary btn-block btn-lg" >LIKE</span>
      </div>

    </div>

    <div class="section group">
      <div class="col span_1_of_12" push></div>
      <div class="col span_10_of_12">
        CARGAR COMENTARIOS
      </div>
    </div>

  </div>
</div>