config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'browse'  => 'users#index'
  get 'mycomics' => 'static_pages#mycomics'
  get 'test'   => 'static_pages#test'
  get 'test/test1'   => 'static_pages#test1', as: :test_test1
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :comments,          only: [:create, :destroy]
  resources :comics do
    resources :pages
  end
  resources :relationships,       only: [:create, :destroy]

end

app/views/layouts/_comic_home.html.erb
<div class="col span_12_of_12">
<div class="content_comic">
    <div class="section group">
      <%= render 'layouts/comics_banner' %>
    </div>

    <div class="section group">
      <div class="col span_3_of_12">

        <div class="col span_11_of_12">
        <h2>Last Updates</h2>

        <ul class="">

          <li><%= link_to "Comic1", '#' %></li>

          <li><%= link_to "Comic2", '#' %></li>
          <li><%= link_to "Comic3", '#' %></li>
          ...
          <li><%= link_to "Archive", '#' %></li>

        </ul>
        </div>

        <div class="col span_11_of_12">
          <h2>Author(s)</h2>

          <ul class="">

            <li><%= link_to "User1", '#' %></li>

            <li><%= link_to "User2", '#' %></li>



          </ul>

        </div>

      </div>

      <div class="col span_6_of_12">
        <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>

        <%= yield %>

      </div>
      <div class="col span_3_of_12">
        <button type="button" class="btn btn-primary btn-lg btn-block">LIKE</button>
        <button type="button" class="btn btn-primary btn-lg btn-block">FOLLOW</button>

      </div>
      <div class="col span_3_of_12">
        <h2>Characters</h2>
        Lorem ipsum
      </div>
    </div>


</div>
</div>

app/views/layouts/_comic_navigation.html.erb
<div class="section group">
  <div class="col span_1_of_12" push></div>
  <div class="col span_10_of_12">
    <ul class="nav navbar-nav nav-center">
      <li><%= link_to "FIRST", '#' %></li>
      <li><%= link_to "PREV", '#' %></li>
      <li><%= link_to "NEXT", '#' %></li>
      <li><%= link_to "LAST", '#' %></li>
    </ul>
  </div>
</div>

app/views/layouts/_comics_banner.html.erb
<div class="col span_1_of_12" push></div>
<div class="col span_10_of_12">
<div class="banner">

  <img class="banner" src="http://www.praguerace.com/images/logo.jpg">
</div>
</div>

app/views/layouts/_container_about.html.erb
<div class="section group">
  <div class="col span_1_of_12">

  </div>
  <div class="col span_10_of_12">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= yield %>
  </div>

</div>

app/views/layouts/_container_browse.html.erb
<div class="section group">

  <div class="col span_9_of_12 browse">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= yield %>
  </div>

  <div class="col span_3_of_12">
    <h2>Search</h2>
    <div class="ui-widget">
      <label for="tags">Tags: </label>
      <input id="tags">
    </div>

    <hr>


    <h2>Filter by Genre</h2>
    <div class="checkbox">
      <label><input type="checkbox" value="">Option 1</label>
    </div>
    <div class="checkbox">
      <label><input type="checkbox" value="">Option 2</label>
    </div>
    <div class="checkbox disabled">
      <label><input type="checkbox" value="">Option 3</label>
    </div>

    <hr>
    <h2>Order by</h2>

    <div class="f">
      <select class="form-control" id="sel1">
        <option>By Date</option>
        <option>Popular</option>
        <option>Top ranked</option>
      </select>
    </div>

    <hr>
  </div>

</div>

app/views/layouts/_container_page.html.erb
<div class="section group">
<div class="content_page">
  <div class="section group">
  <%= render 'layouts/comics_banner' %>
  </div>

<%= render 'layouts/comic_navigation' %>


<div class="section group">
  <div class="col span_1_of_12" push></div>
  <div class="col span_10_of_12">
    <%= yield %>
  </div>
</div>

  <%= render 'layouts/comic_navigation' %>

  <div class="section group">
    <div class="col span_1_of_12" push></div>
    <div class="col span_10_of_12">
      <p>
  <%= yield(:author_comment) %>
      </p>
    </div>
  </div>

  <div class="section group">
    <div class="col span_1_of_12" push></div>
    <div class="col span_7_of_12">
        <%= text_area_tag(:message, "Hi, nice site", size: "10x6") %>
      <div class="col span_4_of_12" style="margin-left: 0px">
        <span class="btn btn-default btn-block btn-lg" >Send</span>
      </div>
    </div>
    <div class="col span_3_of_12">
      <span class="btn btn-primary btn-block btn-lg" >FOLLOW</span>
      <span class="btn btn-primary btn-block btn-lg" >LIKE</span>
    </div>

  </div>

  <div class="section group">
    <div class="col span_1_of_12" push></div>
    <div class="col span_10_of_12">
      CARGAR COMENTARIOS
    </div>
  </div>

</div>
</div>

app/views/layouts/_footer.html.erb
  <nav>
    <ul>
      <li><%= link_to "About",   'about_path' %></li>
      <li><%= link_to "Browse", 'browse_path' %></li>
    </ul>
  </nav>

app/views/layouts/_header.html.erb
<div class="section group">
  <div class="col-md-12" style="background-color:#0f4f62">

  <div class="col-md-8">

  <div class="container left">
    <nav>
      <ul class="nav navbar-nav nav_header" >
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "About",    about_path %></li>
        <li><%= link_to "Browse",    comics_path %></li>
        <li><%= link_to "Forum",    '#', :target => "_blank" %></li>

      </ul>
    </nav>
  </div>

  </div>

  <div class="col-md-1 push"></div>
  <% if logged_in? %>
  <div class="col-md-3">
  <div class="container right">
    <nav>
      <ul class="nav navbar-right navbar-nav" >
        <li><%= link_to "Profile",    current_user %></li>
        <li><%= link_to "My Comics",  mycomics_path %></li>

      </ul>
    </nav>
  </div>

  </div>
      <% end %>

  </div>
</div>

app/views/layouts/_login_menu.html.erb
<nav>
  <ul class="nav navbar-nav login-menu">
    <% if logged_in? %>
        <li><%= link_to "Users", users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Settings", '#' %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: "delete" %>
            </li>
          </ul>
        </li>
    <% else %>
        <li><%= link_to "Sign up", signup_path %></li>
        <li><%= link_to "Log in", login_path %></li>

    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Comic Fans</title>

  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
</head>
<body>
<div class="wrapper">
<header class="navbar ">
  <div class="section group">
    <div class="col span_12_of_12">
      <div class="col span_4_of_12">
        <div class="navbar-brand">
          <%= link_to 'COMIC FANS',    root_path %>
        </div>
      </div>
      <div class="col span_6_of_12 push">
        espacio
      </div>

      <div class="col span_2_of_12">
        <%= render 'layouts/login_menu' %>
      </div>
      <div class="" >
        <%= render 'layouts/header' %>
      </div>
    </div>
  </div>

</header>

  <% if current_page?(users_path) %>


  <% end %>

<div class="content">
  <% if current_page?(root_path) %>
    <%= render 'layouts/container_home' %>
  <% elsif current_page?(test_test1_path) %>
      <%= render 'layouts/container_page' %>

  <% elsif current_page?(comics_path)%>
      <%= render 'layouts/container_browse'  %>

  <% elsif current_page?(test_path)%>
      <%= render 'layouts/comic_home'  %>

    <% else 'layouts/container_page'%>
       <%= render 'layouts/container_about'  %>

   <% end %>


</div>



<footer class="footer">
  <div class="section group">
    <div class="col span_12_of_12">
      <%= render 'layouts/footer' %>
    </div>
  </div>

</footer>
</div>
</body>
</html>